theme: jekyll-theme-leap-day

title: XivRUS (alpha)
description: Проект русской локализации для FINAL FANTASY XIV
locale: ru-RU
show_downloads: true

kramdown:
  input: GFM
  auto_ids: true
  transliterated_header_ids: true

github:
  rus_url: https://github.com/endervad/ffxiv_translation/releases/download/v0.5.0/RUS-0.5.0-2022-07-05.ttmp2
  ruen_url: https://github.com/endervad/ffxiv_translation/releases/download/v0.5.0/RUEN-0.5.0-2022-07-05.ttmp2
